# Generated by Django 5.1.3 on 2024-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=18)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('room_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('vacant', '空房'), ('occupied', '已入住')], default='vacant', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('finance', '账务管理人员'), ('housing', '住房管理人员'), ('catering', '餐饮管理人员'), ('inventory', '库存管理人员'), ('manager', '总经理')], default='manager', max_length=10),
        ),
    ]
