# Generated by Django 5.1.3 on 2024-11-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '系统管理员'), ('finance', '账务管理人员'), ('housing', '住房管理人员'), ('catering', '餐饮管理人员'), ('inventory', '库存管理人员'), ('manager', '总经理')], default='manager', max_length=10),
        ),
    ]
