# Generated by Django 5.1.3 on 2024-11-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
