# Generated by Django 5.1.3 on 2024-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_table_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
