# Generated by Django 5.1.3 on 2024-11-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_number_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='table',
            name='table_status',
            field=models.CharField(choices=[('vacant', '空闲'), ('occupied', '已占用')], default='vacant', max_length=10),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('check_in_time', models.DateTimeField()),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.table')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
