# Generated by Django 5.1.3 on 2024-11-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_dish_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
