# Generated by Django 5.1.3 on 2024-11-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_customer_check_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='check_in_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
