# Generated by Django 5.1.3 on 2024-11-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_customer_check_in_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='check_out_date',
            new_name='check_out_time',
        ),
    ]
