# Generated by Django 5.1.3 on 2024-11-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_room_price_alter_room_id_card_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
