# Generated by Django 5.1.3 on 2024-11-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_room_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
