# Generated by Django 5.1.3 on 2024-11-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_alter_finance_finance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
