# Generated by Django 5.1.3 on 2024-11-27 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_alter_finance_responsible_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
