# Generated by Django 5.1.3 on 2024-11-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_finance_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seat_type',
            field=models.CharField(choices=[('大厅', '大厅'), ('包厢', '包厢')], default='大厅', max_length=10),
            preserve_default=False,
        ),
    ]
