# Generated by Django 5.1.3 on 2024-11-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_alter_room_status_alter_table_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
