# Generated by Django 5.1.3 on 2024-11-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_finance_additional_service_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
